# .github/workflows/ci.yml
name: Django CI

on:
  push:
    branches:
      - developer
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: contenedor_dv
          POSTGRES_USER: contenedor_user_root
          POSTGRES_PASSWORD: 12345
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DB_HOST: localhost
      DB_PORT: 5432
      POSTGRES_DB: contenedor_dv
      POSTGRES_USER: contenedor_user_root
      POSTGRES_PASSWORD: 12345
      SECRET_KEY: "fake-key"
      DEBUG: "1"
      ALLOWED_HOSTS: localhost,127.0.0.1
      DJANGO_SETTINGS_MODULE: core.settings

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run migrations and tests
        run: |
          python manage.py migrate
          python manage.py test
